Train:
  batch_size: 12
  learning_rate: 0.1
  reg: 0.000001
  epochs: 10
  momentum: 0.9
  debug: True

Model:
  type: TwoLayerNet # SoftmaxRegression or TwoLayerNet
  hidden_size: 256 # only applicable for TwolayerNet
  